### ISSUE TITLE
Problem with installation packaging

### ISSUE THREAD

**Issue by brentonmaas** [gyselroth/balloon#455]
#### Describe the bug
after running make install it stops with the following error:
cp: cannot stat ‘./packaging/balloon-jobs.service.systemd’: No such file or directory
make: *** [""/"usr/share/balloon"] Error 1

#### To Reproduce
sudo make install within the balloon folder

#### Expected behavior
Installation to complete

#### Environment
 - balloon server version: v2.4.2
 - Deployed as: compiled manually
 - PHP version: 7.3
 - MongoDB version: e.g. v3.4.18

**Comment by raffis** [comment]
Thanks for the report.
Is this really for v2.4.2? If you should upgrade, this release is quite old.
Anyway this issue has been fixed in master, was a follow up from #415.

Is there a reason you want to manually install? The installation is quite complex and requires various services to be manually deployed. You should deploy balloon using docker-compose or a helm chart (https://gyselroth.github.io/balloon-docs/server/installation/)
